### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [james-pridge/firstime#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by james-pridge** [comment]
Hey thanks for the tidbit. I had kind of hoped the lesson building splurty would have included that. I even asked in the lesson forum about it that I had noticed that it seemed stretched on my s8+ and was told the code looked fine and that was no issue. It does look better. I chose not to include zooming as it seemed kind of pointless. Thoughts?
Also the two screenshots below show my site view from localhost on my laptop and then through the heroku link. The site looks weird, quotes look too far to the right on the localhost. Is there a particular reason? Both have been synced.

![heroku](https://user-images.githubusercontent.com/27582793/30514600-f1c0d05c-9add-11e7-91bc-294094d8439b.jpg)
![localhost](https://user-images.githubusercontent.com/27582793/30514601-f1c283de-9add-11e7-9425-1e938d7357e6.jpg)

**Comment by Mikeysax** [comment]
Hey James,

The mobile meta tag is given as extra if you progress at a decent pace. Our focus is helping you develop a solid foundation and we try to only give tasks to those who are ready for them. Ultimately, my big suggestion is to try not to focus so much on the end result (tiny things like inconsistencies between browsers and other weird styling things, etc.) and more about the process and deeper understanding of how everything works together. Once you understand this in a more natural way, you can easily fix things like this because we've taught you how to fish and not give you the fish (if you know what I mean).

As for the differences between heroku and localhost, it looks like some styles or assets are not loading on one or the other, or there are different font sizes. It's hard to say just by looking at the screenshots, but it would be a great thing to bring up to your Mentor and ask about how you can debug this issue and use google dev tools to inspect and debug CSS and other issues.

Hope this helps and good job adding the meta tag :+1:

**Comment by james-pridge** [comment]
Ok. Thanks for all the advice. I am a perfectionist by nature being a virgo
so it's always the little things that bug me. It's not the first time I've
been told to refocus my attention on the minor issues. Thanks for being so
forward.
Ohh I didn't realize I was doing that good. I'm glad to hear it. I really
want to succeed at this so that's a good motivation. I'll do my best to
keep it up.
I'll def talk to my mentor about debugging the issue. I have an idea or two
of my own

James
